apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltweet
  labels:
    app: ltweet
spec:
  selector:
    matchLabels:
      app: ltweet
  replicas: 1
  template:
    metadata:
      labels:
        app: ltweet
    spec:
      containers:
      - name: ltweet 
        image: aravindmetku01/ltweet:1.0
        ports:
        - containerPort: 80
