apiVersion: v1
kind: Service
metadata:
  labels:
    app: ltweet-svc
  name: ltweet
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: ltweet
